CREATE TABLE IF NOT EXISTS "Padres" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS "Hijos" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre VARCHAR(20),
    hijode INTEGER,
    FOREIGN KEY(hijode) REFERENCES Padres(id)
);